version: '3.8'

services:
  mysql:
    image: mysql
    container_name: store
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: store
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/