version: '3.8'
services:
  mongo:
    container_name: monguito
    image: mongo:6.0.4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodata:/data/db
    environment:
       MONGO_INITDB_ROOT_USERNAME: user
       MONGO_INITDB_ROOT_PASSWORD: password
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --requirepass yourpassword
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
volumes:
  redis_data:
    driver: local